CREATE DATABASE AJ_WINDOW_FUNCTIONS;
USE AJ_WINDOW_FUNCTIONS;

CREATE  TABLE AJ_EMPLOYEE_RAW
(
Employee_ID INT,
Name Varchar(20),
Salary float(2)
);

INSERT INTO AJ_EMPLOYEE_RAW (EMPLOYEE_ID,NAME,SALARY) VALUES (100,'JENIFER',4400);
INSERT INTO AJ_EMPLOYEE_RAW (EMPLOYEE_ID,NAME,SALARY) VALUES (100,'JENIFER',4400);
INSERT INTO AJ_EMPLOYEE_RAW (EMPLOYEE_ID,NAME,SALARY) VALUES (101,'Michael',13000);
INSERT INTO AJ_EMPLOYEE_RAW (EMPLOYEE_ID,NAME,SALARY) VALUES (101,'Michael',13000);
INSERT INTO AJ_EMPLOYEE_RAW (EMPLOYEE_ID,NAME,SALARY) VALUES (102,'Pat',6000);
INSERT INTO AJ_EMPLOYEE_RAW (EMPLOYEE_ID,NAME,SALARY) VALUES (102,'Pat',6000);
INSERT INTO AJ_EMPLOYEE_RAW (EMPLOYEE_ID,NAME,SALARY) VALUES (103,'Den',11000);

SELECT * FROM AJ_EMPLOYEE_RAW;

-- ORDER BY IS NOT MANDATORY UNLIKE SNOWFLAKE IN MYSQL
select *,ROW_NUMBER() OVER() AS R_NUMBER FROM AJ_EMPLOYEE_RAW;

DELETE FROM 
(
   SELECT *,ROW_NUMBER() OVER(ORDER BY SALARY) AS R_NUMBER FROM AJ_EMPLOYEE_RAW AS TEST
)   
WHERE TEST.R_NUMBER IN (2,5,7);